package com.goody.nus.se.gomoku.user.model.dao.customer;

import com.goody.nus.se.gomoku.user.model.entity.UserToken;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

/**
 * Customer Mapper for UserToken
 * Add custom queries here
 * Generated by MyBatis Generator Customer Mapper Plugin
 */
@Mapper
public interface CustomerUserTokenMapper {

    /**
     * Find user token by user ID
     *
     * @param userId User ID
     * @return UserToken entity, null if not found
     */
    @Select("SELECT id, user_id, refresh_token, expires_at, created_at, updated_at " +
            "FROM user_token WHERE user_id = #{userId}")
    UserToken selectByUserId(@Param("userId") Long userId);

    /**
     * Find user token by refresh token
     *
     * @param refreshToken Refresh Token
     * @return UserToken entity, null if not found
     */
    @Select("SELECT id, user_id, refresh_token, expires_at, created_at, updated_at " +
            "FROM user_token WHERE refresh_token = #{refreshToken}")
    UserToken selectByRefreshToken(@Param("refreshToken") String refreshToken);

    /**
     * Delete user token by user ID
     *
     * @param userId User ID
     * @return number of affected rows
     */
    @Delete("DELETE FROM user_token WHERE user_id = #{userId}")
    int deleteByUserId(@Param("userId") Long userId);
}