package com.goody.nus.se.gomoku.user.model.dao.customer;

import com.goody.nus.se.gomoku.user.model.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Optional;

/**
 * Customer Mapper for User
 * Add custom queries here
 * Generated by MyBatis Generator Customer Mapper Plugin
 */
@Mapper
public interface CustomerUserMapper {

    /**
     * Find user by email
     *
     * @param email email address
     * @return Optional User entity
     */
    @Select("SELECT * FROM user WHERE email = #{email}")
    Optional<User> findByEmail(@Param("email") String email);

    /**
     * Find user by nickname
     *
     * @param nickname user nickname
     * @return Optional User entity
     */
    @Select("SELECT * FROM user WHERE nickname = #{nickname}")
    Optional<User> findByNickname(@Param("nickname") String nickname);

    /**
     * Check if email exists
     *
     * @param email email address
     * @return true if exists, false otherwise
     */
    @Select("SELECT COUNT(*) > 0 FROM user WHERE email = #{email}")
    boolean existsByEmail(@Param("email") String email);

    /**
     * Check if nickname exists
     *
     * @param nickname user nickname
     * @return true if exists, false otherwise
     */
    @Select("SELECT COUNT(*) > 0 FROM user WHERE nickname = #{nickname}")
    boolean existsByNickname(@Param("nickname") String nickname);
}
