package com.goody.nus.se.gomoku.ranking.model.dto;

import com.goody.nus.se.gomoku.ranking.model.entity.LeaderboardRule;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for LeaderboardRule
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LeaderboardRuleDTO {
    /**
     * Primary key
     */
    private Long id;

    /**
     * Leaderboard start time (Unix timestamp)
     */
    private Integer startTime;

    /**
     * Leaderboard end time (Unix timestamp)
     */
    private Integer endTime;

    /**
     * Leaderboard type
     */
    private String type;

    /**
     * Linked score rule ID
     */
    private Long ruleId;

    /**
     * Leaderboard description
     */
    private String description;

    /**
     * Creation time
     */
    private LocalDateTime createdTime;

    /**
     * Update time
     */
    private LocalDateTime updatedTime;

    public static LeaderboardRuleDTO fromEntity(LeaderboardRule entity) {
        if (entity == null) {
            return null;
        }
        
        return LeaderboardRuleDTO.builder()
            .id(entity.getId())
            .startTime(entity.getStartTime())
            .endTime(entity.getEndTime())
            .type(entity.getType())
            .ruleId(entity.getRuleId())
            .description(entity.getDescription())
            .createdTime(entity.getCreatedTime())
            .updatedTime(entity.getUpdatedTime())
            .build();
    }

    public LeaderboardRule toEntity() {
        return new LeaderboardRule()
            .withId(this.id)
            .withStartTime(this.startTime)
            .withEndTime(this.endTime)
            .withType(this.type)
            .withRuleId(this.ruleId)
            .withDescription(this.description)
            .withCreatedTime(this.createdTime)
            .withUpdatedTime(this.updatedTime)
            ;
    }
}