package com.goody.nus.se.gomoku.ranking.model.dto;

import com.goody.nus.se.gomoku.ranking.model.entity.Level;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for Level
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LevelDTO {
    /**
     * Level ID
     */
    private Long id;

    /**
     * Experience required to reach the next level
     */
    private Integer expRequired;

    /**
     * Creation time
     */
    private LocalDateTime createdTime;

    /**
     * Update time
     */
    private LocalDateTime updatedTime;

    public static LevelDTO fromEntity(Level entity) {
        if (entity == null) {
            return null;
        }
        
        return LevelDTO.builder()
            .id(entity.getId())
            .expRequired(entity.getExpRequired())
            .createdTime(entity.getCreatedTime())
            .updatedTime(entity.getUpdatedTime())
            .build();
    }

    public Level toEntity() {
        return new Level()
            .withId(this.id)
            .withExpRequired(this.expRequired)
            .withCreatedTime(this.createdTime)
            .withUpdatedTime(this.updatedTime)
            ;
    }
}