package com.goody.nus.se.gomoku.ranking.model.dto;

import com.goody.nus.se.gomoku.ranking.model.entity.LevelRule;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for LevelRule
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LevelRuleDTO {
    /**
     * Primary key
     */
    private Long id;

    /**
     * Game mode type
     */
    private String modeType;

    /**
     * Match result
     */
    private String matchResult;

    /**
     * Experience value change
     */
    private Integer expValue;

    /**
     * Rule description
     */
    private String description;

    /**
     * Creation time
     */
    private LocalDateTime createdTime;

    /**
     * Update time
     */
    private LocalDateTime updatedTime;

    public static LevelRuleDTO fromEntity(LevelRule entity) {
        if (entity == null) {
            return null;
        }
        
        return LevelRuleDTO.builder()
            .id(entity.getId())
            .modeType(entity.getModeType())
            .matchResult(entity.getMatchResult())
            .expValue(entity.getExpValue())
            .description(entity.getDescription())
            .createdTime(entity.getCreatedTime())
            .updatedTime(entity.getUpdatedTime())
            .build();
    }

    public LevelRule toEntity() {
        return new LevelRule()
            .withId(this.id)
            .withModeType(this.modeType)
            .withMatchResult(this.matchResult)
            .withExpValue(this.expValue)
            .withDescription(this.description)
            .withCreatedTime(this.createdTime)
            .withUpdatedTime(this.updatedTime)
            ;
    }
}