package com.goody.nus.se.gomoku.ranking.model.dto;

import com.goody.nus.se.gomoku.ranking.model.entity.Ranking;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for Ranking
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class RankingDTO {
    /**
     * Primary key
     */
    private Long id;

    /**
     * Player ID
     */
    private Long userId;

    /**
     * Leaderboard ID
     */
    private Long leaderboardRuleId;

    /**
     * Player total experience
     */
    private Integer totalExp;

    /**
     * Current level ID
     */
    private Long levelId;

    /**
     * Current total score (only changes in ranked mode)
     */
    private Integer currentTotalScore;

    /**
     * Current ranking position (refresh periodically)
     */
    private Integer rankPosition;

    /**
     * Creation time
     */
    private LocalDateTime createdTime;

    /**
     * Update time
     */
    private LocalDateTime updatedTime;

    public static RankingDTO fromEntity(Ranking entity) {
        if (entity == null) {
            return null;
        }
        
        return RankingDTO.builder()
            .id(entity.getId())
            .userId(entity.getUserId())
            .leaderboardRuleId(entity.getLeaderboardRuleId())
            .totalExp(entity.getTotalExp())
            .levelId(entity.getLevelId())
            .currentTotalScore(entity.getCurrentTotalScore())
            .rankPosition(entity.getRankPosition())
            .createdTime(entity.getCreatedTime())
            .updatedTime(entity.getUpdatedTime())
            .build();
    }

    public Ranking toEntity() {
        return new Ranking()
            .withId(this.id)
            .withUserId(this.userId)
            .withLeaderboardRuleId(this.leaderboardRuleId)
            .withTotalExp(this.totalExp)
            .withLevelId(this.levelId)
            .withCurrentTotalScore(this.currentTotalScore)
            .withRankPosition(this.rankPosition)
            .withCreatedTime(this.createdTime)
            .withUpdatedTime(this.updatedTime)
            ;
    }
}