package com.goody.nus.se.gomoku.ranking.model.dto;

import com.goody.nus.se.gomoku.ranking.model.entity.Score;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for Score
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ScoreDTO {
    /**
     * Primary key
     */
    private Long id;

    /**
     * Leaderboard ID
     */
    private Long leaderboardRuleId;

    /**
     * Player ID
     */
    private Long userId;

    /**
     * Match ID (from match module)
     */
    private Long matchId;

    /**
     * Score rule ID (from score_rule)
     */
    private Long ruleId;

    /**
     * Score change in this match
     */
    private Integer scoreChange;

    /**
     * Player total score after match
     */
    private Integer finalScore;

    /**
     * Match result
     */
    private String matchResult;

    /**
     * Creation time
     */
    private LocalDateTime createdTime;

    /**
     * Update time
     */
    private LocalDateTime updatedTime;

    public static ScoreDTO fromEntity(Score entity) {
        if (entity == null) {
            return null;
        }
        
        return ScoreDTO.builder()
            .id(entity.getId())
            .leaderboardRuleId(entity.getLeaderboardRuleId())
            .userId(entity.getUserId())
            .matchId(entity.getMatchId())
            .ruleId(entity.getRuleId())
            .scoreChange(entity.getScoreChange())
            .finalScore(entity.getFinalScore())
            .matchResult(entity.getMatchResult())
            .createdTime(entity.getCreatedTime())
            .updatedTime(entity.getUpdatedTime())
            .build();
    }

    public Score toEntity() {
        return new Score()
            .withId(this.id)
            .withLeaderboardRuleId(this.leaderboardRuleId)
            .withUserId(this.userId)
            .withMatchId(this.matchId)
            .withRuleId(this.ruleId)
            .withScoreChange(this.scoreChange)
            .withFinalScore(this.finalScore)
            .withMatchResult(this.matchResult)
            .withCreatedTime(this.createdTime)
            .withUpdatedTime(this.updatedTime)
            ;
    }
}