package com.goody.nus.se.gomoku.ranking.model.dto;

import com.goody.nus.se.gomoku.ranking.model.entity.ScoreRule;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for ScoreRule
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ScoreRuleDTO {
    /**
     * Primary key
     */
    private Long id;

    /**
     * Rule name (e.g., Standard, Season1, etc.)
     */
    private String ruleName;

    /**
     * RANKED mode WIN score change
     */
    private Integer rankedWinScore;

    /**
     * RANKED mode LOSE score change
     */
    private Integer rankedLoseScore;

    /**
     * RANKED mode DRAW score change
     */
    private Integer rankedDrawScore;

    /**
     * CASUAL mode WIN score change
     */
    private Integer casualWinScore;

    /**
     * CASUAL mode LOSE score change
     */
    private Integer casualLoseScore;

    /**
     * CASUAL mode DRAW score change
     */
    private Integer casualDrawScore;

    /**
     * PRIVATE mode WIN score change
     */
    private Integer privateWinScore;

    /**
     * PRIVATE mode LOSE score change
     */
    private Integer privateLoseScore;

    /**
     * PRIVATE mode DRAW score change
     */
    private Integer privateDrawScore;

    /**
     * Rule description
     */
    private String description;

    /**
     * Creation time
     */
    private LocalDateTime createdTime;

    /**
     * Update time
     */
    private LocalDateTime updatedTime;

    public static ScoreRuleDTO fromEntity(ScoreRule entity) {
        if (entity == null) {
            return null;
        }
        
        return ScoreRuleDTO.builder()
            .id(entity.getId())
            .ruleName(entity.getRuleName())
            .rankedWinScore(entity.getRankedWinScore())
            .rankedLoseScore(entity.getRankedLoseScore())
            .rankedDrawScore(entity.getRankedDrawScore())
            .casualWinScore(entity.getCasualWinScore())
            .casualLoseScore(entity.getCasualLoseScore())
            .casualDrawScore(entity.getCasualDrawScore())
            .privateWinScore(entity.getPrivateWinScore())
            .privateLoseScore(entity.getPrivateLoseScore())
            .privateDrawScore(entity.getPrivateDrawScore())
            .description(entity.getDescription())
            .createdTime(entity.getCreatedTime())
            .updatedTime(entity.getUpdatedTime())
            .build();
    }

    public ScoreRule toEntity() {
        return new ScoreRule()
            .withId(this.id)
            .withRuleName(this.ruleName)
            .withRankedWinScore(this.rankedWinScore)
            .withRankedLoseScore(this.rankedLoseScore)
            .withRankedDrawScore(this.rankedDrawScore)
            .withCasualWinScore(this.casualWinScore)
            .withCasualLoseScore(this.casualLoseScore)
            .withCasualDrawScore(this.casualDrawScore)
            .withPrivateWinScore(this.privateWinScore)
            .withPrivateLoseScore(this.privateLoseScore)
            .withPrivateDrawScore(this.privateDrawScore)
            .withDescription(this.description)
            .withCreatedTime(this.createdTime)
            .withUpdatedTime(this.updatedTime)
            ;
    }

    /**
     * Get score value by mode type and match result
     *
     * @param modeType game mode type (RANKED, CASUAL, PRIVATE)
     * @param matchResult match result (WIN, LOSE, DRAW)
     * @return score value, 0 if not found or null
     */
    public Integer getScoreValue(String modeType, String matchResult) {
        if (modeType == null || matchResult == null) {
            return 0;
        }

        String mode = modeType.toUpperCase();
        String result = matchResult.toUpperCase();

        switch (mode) {
            case "RANKED":
                switch (result) {
                    case "WIN": return rankedWinScore != null ? rankedWinScore : 0;
                    case "LOSE": return rankedLoseScore != null ? rankedLoseScore : 0;
                    case "DRAW": return rankedDrawScore != null ? rankedDrawScore : 0;
                }
                break;
            case "CASUAL":
                switch (result) {
                    case "WIN": return casualWinScore != null ? casualWinScore : 0;
                    case "LOSE": return casualLoseScore != null ? casualLoseScore : 0;
                    case "DRAW": return casualDrawScore != null ? casualDrawScore : 0;
                }
                break;
            case "PRIVATE":
                switch (result) {
                    case "WIN": return privateWinScore != null ? privateWinScore : 0;
                    case "LOSE": return privateLoseScore != null ? privateLoseScore : 0;
                    case "DRAW": return privateDrawScore != null ? privateDrawScore : 0;
                }
                break;
        }

        return 0;
    }
}