package com.goody.nus.se.gomoku.gomoku.model.entity;

import jakarta.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   Game Room Table
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table game_room
 */
public class GameRoom implements Serializable {
    /**
     * Database Column Remarks:
     *   Room ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   Room code for joining
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.room_code")
    private String roomCode;

    /**
     * Database Column Remarks:
     *   First player user ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.player1_id")
    private Long player1Id;

    /**
     * Database Column Remarks:
     *   Second player user ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.player2_id")
    private Long player2Id;

    /**
     * Database Column Remarks:
     *   Match type (0=casual, 1=ranked)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.type")
    private Byte type;

    /**
     * Database Column Remarks:
     *   Room status (0=waiting, 1=matched, 2=playing, 3=finished)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.status")
    private Byte status;

    /**
     * Database Column Remarks:
     *   Creation time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.created_at")
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   Update time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.updated_at")
    private LocalDateTime updatedAt;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.room_code")
    public String getRoomCode() {
        return roomCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withRoomCode(String roomCode) {
        this.setRoomCode(roomCode);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.room_code")
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode == null ? null : roomCode.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.player1_id")
    public Long getPlayer1Id() {
        return player1Id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withPlayer1Id(Long player1Id) {
        this.setPlayer1Id(player1Id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.player1_id")
    public void setPlayer1Id(Long player1Id) {
        this.player1Id = player1Id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.player2_id")
    public Long getPlayer2Id() {
        return player2Id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withPlayer2Id(Long player2Id) {
        this.setPlayer2Id(player2Id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.player2_id")
    public void setPlayer2Id(Long player2Id) {
        this.player2Id = player2Id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.type")
    public Byte getType() {
        return type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withType(Byte type) {
        this.setType(type);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.type")
    public void setType(Byte type) {
        this.type = type;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.status")
    public Byte getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.status")
    public void setStatus(Byte status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.created_at")
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withCreatedAt(LocalDateTime createdAt) {
        this.setCreatedAt(createdAt);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.created_at")
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.updated_at")
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public GameRoom withUpdatedAt(LocalDateTime updatedAt) {
        this.setUpdatedAt(updatedAt);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: game_room.updated_at")
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GameRoom other = (GameRoom) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoomCode() == null ? other.getRoomCode() == null : this.getRoomCode().equals(other.getRoomCode()))
            && (this.getPlayer1Id() == null ? other.getPlayer1Id() == null : this.getPlayer1Id().equals(other.getPlayer1Id()))
            && (this.getPlayer2Id() == null ? other.getPlayer2Id() == null : this.getPlayer2Id().equals(other.getPlayer2Id()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoomCode() == null) ? 0 : getRoomCode().hashCode());
        result = prime * result + ((getPlayer1Id() == null) ? 0 : getPlayer1Id().hashCode());
        result = prime * result + ((getPlayer2Id() == null) ? 0 : getPlayer2Id().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        return result;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: game_room")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomCode=").append(roomCode);
        sb.append(", player1Id=").append(player1Id);
        sb.append(", player2Id=").append(player2Id);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}