package com.goody.nus.se.gomoku.ranking.service.interfaces;

import com.goody.nus.se.gomoku.ranking.model.dto.LeaderboardRuleDTO;
import java.util.List;

/**
 * Service interface for LeaderboardRule
 * Generated by MyBatis Generator Service Plugin
 */
public interface ILeaderboardRuleService {
    /**
     * Save a single entity
     *
     * @param dto the DTO object to save
     * @return primary key id of saved entity, null if failed
     */
    Long save(LeaderboardRuleDTO dto);

    /**
     * Batch save entities
     *
     * @param dtoList list of DTO objects to save
     * @return number of affected rows
     */
    int saveBatch(List<LeaderboardRuleDTO> dtoList);

    /**
     * Update entity by primary key
     *
     * @param dto the DTO object to update, must contain primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int update(LeaderboardRuleDTO dto);

    /**
     * Delete entity by primary key
     *
     * @param id Primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int deleteById(Long id);

    /**
     * Find entity by primary key
     *
     * @param id Primary key
     * @return DTO object, null if not found
     */
    LeaderboardRuleDTO findById(Long id);

    /**
     * Find all entities
     *
     * @return list of DTO objects
     */
    List<LeaderboardRuleDTO> findAll();

    // ==================== Custom Query Methods ====================

    /**
     * Find active leaderboard rules by current time
     *
     * @param currentTime current Unix timestamp (in seconds)
     * @return list of active leaderboard rules
     */
    List<LeaderboardRuleDTO> findActiveRules(int currentTime);

    /**
     * Find leaderboard rule by type
     *
     * @param type leaderboard type (DAILY, MONTHLY, SEASONAL, TOTAL)
     * @return leaderboard rule or null if not found
     */
    LeaderboardRuleDTO findByType(String type);

    /**
     * Find active leaderboard rule by type and current time
     *
     * @param type leaderboard type
     * @param currentTime current Unix timestamp (in seconds)
     * @return active leaderboard rule or null if not found
     */
    LeaderboardRuleDTO findActiveRuleByType(String type, int currentTime);
}