package com.goody.nus.se.gomoku.ranking.service.interfaces;

import com.goody.nus.se.gomoku.ranking.model.dto.LevelRuleDTO;
import java.util.List;

/**
 * Service interface for LevelRule
 * Generated by MyBatis Generator Service Plugin
 */
public interface ILevelRuleService {
    /**
     * Save a single entity
     *
     * @param dto the DTO object to save
     * @return primary key id of saved entity, null if failed
     */
    Long save(LevelRuleDTO dto);

    /**
     * Batch save entities
     *
     * @param dtoList list of DTO objects to save
     * @return number of affected rows
     */
    int saveBatch(List<LevelRuleDTO> dtoList);

    /**
     * Update entity by primary key
     *
     * @param dto the DTO object to update, must contain primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int update(LevelRuleDTO dto);

    /**
     * Delete entity by primary key
     *
     * @param id Primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int deleteById(Long id);

    /**
     * Find entity by primary key
     *
     * @param id Primary key
     * @return DTO object, null if not found
     */
    LevelRuleDTO findById(Long id);

    /**
     * Find all entities
     *
     * @return list of DTO objects
     */
    List<LevelRuleDTO> findAll();

    // ==================== Custom Query Methods ====================

    /**
     * Find level rule by mode type and match result
     *
     * @param modeType game mode type (RANKED, CASUAL, PRIVATE)
     * @param matchResult match result (WIN, LOSE, DRAW)
     * @return level rule DTO or null if not found
     */
    LevelRuleDTO findByModeTypeAndMatchResult(String modeType, String matchResult);
}