package com.goody.nus.se.gomoku.ranking.service.interfaces;

import com.goody.nus.se.gomoku.ranking.model.dto.RankingDTO;
import java.util.List;

/**
 * Service interface for Ranking
 * Generated by MyBatis Generator Service Plugin
 */
public interface IRankingService {
    /**
     * Save a single entity
     *
     * @param dto the DTO object to save
     * @return primary key id of saved entity, null if failed
     */
    Long save(RankingDTO dto);

    /**
     * Batch save entities
     *
     * @param dtoList list of DTO objects to save
     * @return number of affected rows
     */
    int saveBatch(List<RankingDTO> dtoList);

    /**
     * Update entity by primary key
     *
     * @param dto the DTO object to update, must contain primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int update(RankingDTO dto);

    /**
     * Delete entity by primary key
     *
     * @param id Primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int deleteById(Long id);

    /**
     * Find entity by primary key
     *
     * @param id Primary key
     * @return DTO object, null if not found
     */
    RankingDTO findById(Long id);

    /**
     * Find all entities
     *
     * @return list of DTO objects
     */
    List<RankingDTO> findAll();

    // ==================== Custom Query Methods ====================

    /**
     * Find ranking by user ID and leaderboard rule ID
     *
     * @param userId user ID
     * @param leaderboardRuleId leaderboard rule ID
     * @return ranking DTO or null if not found
     */
    RankingDTO findByUserIdAndLeaderboardRuleId(Long userId, Long leaderboardRuleId);

    /**
     * Find top rankings by leaderboard rule ID (ordered by score desc, updatedTime asc, userId asc)
     *
     * @param leaderboardRuleId leaderboard rule ID
     * @param limit max number of results
     * @return list of top rankings
     */
    List<RankingDTO> findTopByLeaderboardRuleId(Long leaderboardRuleId, int limit);

    /**
     * Count rankings by leaderboard rule ID
     *
     * @param leaderboardRuleId leaderboard rule ID
     * @return count of rankings
     */
    long countByLeaderboardRuleId(Long leaderboardRuleId);

    /**
     * Count rankings with score greater than specified value
     *
     * @param leaderboardRuleId leaderboard rule ID
     * @param score score threshold
     * @return count of rankings with higher scores
     */
    long countByLeaderboardRuleIdAndScoreGreaterThan(Long leaderboardRuleId, int score);
}