package com.goody.nus.se.gomoku.ranking.service.interfaces;

import com.goody.nus.se.gomoku.ranking.model.dto.ScoreDTO;
import java.util.List;

/**
 * Service interface for Score
 * Generated by MyBatis Generator Service Plugin
 */
public interface IScoreService {
    /**
     * Save a single entity
     *
     * @param dto the DTO object to save
     * @return primary key id of saved entity, null if failed
     */
    Long save(ScoreDTO dto);

    /**
     * Batch save entities
     *
     * @param dtoList list of DTO objects to save
     * @return number of affected rows
     */
    int saveBatch(List<ScoreDTO> dtoList);

    /**
     * Update entity by primary key
     *
     * @param dto the DTO object to update, must contain primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int update(ScoreDTO dto);

    /**
     * Delete entity by primary key
     *
     * @param id Primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int deleteById(Long id);

    /**
     * Find entity by primary key
     *
     * @param id Primary key
     * @return DTO object, null if not found
     */
    ScoreDTO findById(Long id);

    /**
     * Find all entities
     *
     * @return list of DTO objects
     */
    List<ScoreDTO> findAll();

    // ==================== Custom Query Methods ====================

    /**
     * Find scores by user ID and leaderboard rule ID
     *
     * @param userId user ID
     * @param leaderboardRuleId leaderboard rule ID
     * @return list of scores
     */
    List<ScoreDTO> findByUserIdAndLeaderboardRuleId(Long userId, Long leaderboardRuleId);

    /**
     * Count scores by match ID (for idempotency check)
     *
     * @param matchId match ID
     * @return count of scores for this match
     */
    long countByMatchId(Long matchId);
}