package com.goody.nus.se.gomoku.ranking.service.interfaces;

import com.goody.nus.se.gomoku.ranking.model.dto.ScoreRuleDTO;
import java.util.List;

/**
 * Service interface for ScoreRule
 * Generated by MyBatis Generator Service Plugin
 */
public interface IScoreRuleService {
    /**
     * Save a single entity
     *
     * @param dto the DTO object to save
     * @return primary key id of saved entity, null if failed
     */
    Long save(ScoreRuleDTO dto);

    /**
     * Batch save entities
     *
     * @param dtoList list of DTO objects to save
     * @return number of affected rows
     */
    int saveBatch(List<ScoreRuleDTO> dtoList);

    /**
     * Update entity by primary key
     *
     * @param dto the DTO object to update, must contain primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int update(ScoreRuleDTO dto);

    /**
     * Delete entity by primary key
     *
     * @param id Primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int deleteById(Long id);

    /**
     * Find entity by primary key
     *
     * @param id Primary key
     * @return DTO object, null if not found
     */
    ScoreRuleDTO findById(Long id);

    /**
     * Find all entities
     *
     * @return list of DTO objects
     */
    List<ScoreRuleDTO> findAll();
}