package com.goody.nus.se.gomoku.gomoku.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.gomoku.model.dao.GameRoomDynamicSqlSupport;
import com.goody.nus.se.gomoku.gomoku.model.dao.GameRoomMapper;
import com.goody.nus.se.gomoku.gomoku.model.dao.customer.CustomerGameRoomMapper;
import com.goody.nus.se.gomoku.gomoku.model.dto.GameRoomDTO;
import com.goody.nus.se.gomoku.gomoku.model.entity.GameRoom;
import com.goody.nus.se.gomoku.gomoku.service.interfaces.IGameRoomService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;

/**
 * Service implementation for GameRoom
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class GameRoomServiceImpl implements IGameRoomService {
    @Autowired
    private GameRoomMapper gameRoomMapper;

    @Autowired
    private CustomerGameRoomMapper customerGameRoomMapper;

    @Override
    public Long save(GameRoomDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        GameRoom entity = dto.toEntity();
        int result = gameRoomMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<GameRoomDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<GameRoom> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedAt() == null) {
                        dto.setCreatedAt(LocalDateTime.now());
                    }
                    if (dto.getUpdatedAt() == null) {
                        dto.setUpdatedAt(LocalDateTime.now());
                    }
                })
                .map(GameRoomDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return gameRoomMapper.insertMultiple(entityList);
    }

    @Override
    public int update(GameRoomDTO dto) {
        if (dto == null) {
            return 0;
        }

        GameRoom entity = dto.toEntity();
        return gameRoomMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return gameRoomMapper.deleteByPrimaryKey(id);
    }

    @Override
    public GameRoomDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        GameRoom entity = gameRoomMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? GameRoomDTO.fromEntity(entity) : null;
    }

    @Override
    public List<GameRoomDTO> findAll() {
        List<GameRoom> entityList = gameRoomMapper.select(c -> c);
        return entityList.stream()
                .map(GameRoomDTO::fromEntity)
                .collect(Collectors.toList());
    }

    @Override
    public Long findRoomIdByRoomCode(String roomCode) {
        if (roomCode == null || roomCode.isEmpty()) {
            return null;
        }

        List<GameRoom> result = gameRoomMapper.select(c -> c
                .where(GameRoomDynamicSqlSupport.roomCode, isEqualTo(roomCode))
                .limit(1)
        );

        return result.isEmpty() ? null : result.get(0).getId();
    }
}
