package com.goody.nus.se.gomoku.gomoku.service.interfaces;

import com.goody.nus.se.gomoku.gomoku.model.dto.GameRoomDTO;

import java.util.List;

/**
 * Service interface for GameRoom
 * Generated by MyBatis Generator Service Plugin
 */
public interface IGameRoomService {
    /**
     * Save a single entity
     *
     * @param dto the DTO object to save
     * @return primary key id of saved entity, null if failed
     */
    Long save(GameRoomDTO dto);

    /**
     * Batch save entities
     *
     * @param dtoList list of DTO objects to save
     * @return number of affected rows
     */
    int saveBatch(List<GameRoomDTO> dtoList);

    /**
     * Update entity by primary key
     *
     * @param dto the DTO object to update, must contain primary key
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int update(GameRoomDTO dto);

    /**
     * Delete entity by primary key
     *
     * @param id Room ID
     * @return number of affected rows, 1 for success, 0 for failure
     */
    int deleteById(Long id);

    /**
     * Find entity by primary key
     *
     * @param id Room ID
     * @return DTO object, null if not found
     */
    GameRoomDTO findById(Long id);

    /**
     * Find all entities
     *
     * @return list of DTO objects
     */
    List<GameRoomDTO> findAll();

    /**
     * Find room ID by room code
     *
     * @param roomCode the room code
     * @return room ID, or null if not found
     */
    Long findRoomIdByRoomCode(String roomCode);
}
