package com.goody.nus.se.gomoku.user.model.dto;

import com.goody.nus.se.gomoku.user.model.entity.User;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for User
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UserDTO {
    /**
     * User ID
     */
    private Long id;

    /**
     * Bound email address
     */
    private String email;

    /**
     * User nickname
     */
    private String nickname;

    /**
     * BCrypt password hash
     */
    private String passwordHash;

    /**
     * UUID-based password salt
     */
    private String passwordSalt;

    /**
     * Avatar URL
     */
    private String avatarUrl;

    /**
     * Country
     */
    private String country;

    /**
     * Gender (0=unknown, 1=male, 2=female)
     */
    private Byte gender;

    /**
     * Account status (0=inactive, 1=active, 2=disabled, 3=deleted)
     */
    private Byte status;

    /**
     * Creation time
     */
    private LocalDateTime createdAt;

    /**
     * Update time
     */
    private LocalDateTime updatedAt;

    /**
     * Avatar base64
     */
    private String avatarBase64;

    public static UserDTO fromEntity(User entity) {
        if (entity == null) {
            return null;
        }
        
        return UserDTO.builder()
            .id(entity.getId())
            .email(entity.getEmail())
            .nickname(entity.getNickname())
            .passwordHash(entity.getPasswordHash())
            .passwordSalt(entity.getPasswordSalt())
            .avatarUrl(entity.getAvatarUrl())
            .country(entity.getCountry())
            .gender(entity.getGender())
            .status(entity.getStatus())
            .createdAt(entity.getCreatedAt())
            .updatedAt(entity.getUpdatedAt())
            .avatarBase64(entity.getAvatarBase64())
            .build();
    }

    public User toEntity() {
        return new User()
            .withId(this.id)
            .withEmail(this.email)
            .withNickname(this.nickname)
            .withPasswordHash(this.passwordHash)
            .withPasswordSalt(this.passwordSalt)
            .withAvatarUrl(this.avatarUrl)
            .withCountry(this.country)
            .withGender(this.gender)
            .withStatus(this.status)
            .withCreatedAt(this.createdAt)
            .withUpdatedAt(this.updatedAt)
            .withAvatarBase64(this.avatarBase64)
            ;
    }
}