package com.goody.nus.se.gomoku.user.model.dto;

import com.goody.nus.se.gomoku.user.model.entity.UserToken;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO for UserToken
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UserTokenDTO {
    /**
     * Primary Key
     */
    private Long id;

    /**
     * User ID
     */
    private Long userId;

    /**
     * Refresh Token (UUID)
     */
    private String refreshToken;

    /**
     * Expiration time
     */
    private LocalDateTime expiresAt;

    /**
     * Creation time
     */
    private LocalDateTime createdAt;

    /**
     * Update time
     */
    private LocalDateTime updatedAt;

    public static UserTokenDTO fromEntity(UserToken entity) {
        if (entity == null) {
            return null;
        }

        return UserTokenDTO.builder()
                .id(entity.getId())
                .userId(entity.getUserId())
                .refreshToken(entity.getRefreshToken())
                .expiresAt(entity.getExpiresAt())
                .createdAt(entity.getCreatedAt())
                .updatedAt(entity.getUpdatedAt())
                .build();
    }

    public UserToken toEntity() {
        return new UserToken()
                .withId(this.id)
                .withUserId(this.userId)
                .withRefreshToken(this.refreshToken)
                .withExpiresAt(this.expiresAt)
                .withCreatedAt(this.createdAt)
                .withUpdatedAt(this.updatedAt)
                ;
    }
}
