package com.goody.nus.se.gomoku.gomoku.model.dto;

import com.goody.nus.se.gomoku.gomoku.model.entity.GameRoom;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for GameRoom
 * Generated by MyBatis Generator DTO Plugin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class GameRoomDTO {
    /**
     * Room ID
     */
    private Long id;

    /**
     * Room code for joining
     */
    private String roomCode;

    /**
     * First player user ID
     */
    private Long player1Id;

    /**
     * Second player user ID
     */
    private Long player2Id;

    /**
     * Match type (0=casual, 1=ranked)
     */
    private Byte type;

    /**
     * Room status (0=waiting, 1=matched, 2=playing, 3=finished)
     */
    private Byte status;

    /**
     * Creation time
     */
    private LocalDateTime createdAt;

    /**
     * Update time
     */
    private LocalDateTime updatedAt;

    public static GameRoomDTO fromEntity(GameRoom entity) {
        if (entity == null) {
            return null;
        }
        
        return GameRoomDTO.builder()
            .id(entity.getId())
            .roomCode(entity.getRoomCode())
            .player1Id(entity.getPlayer1Id())
            .player2Id(entity.getPlayer2Id())
            .type(entity.getType())
            .status(entity.getStatus())
            .createdAt(entity.getCreatedAt())
            .updatedAt(entity.getUpdatedAt())
            .build();
    }

    public GameRoom toEntity() {
        return new GameRoom()
            .withId(this.id)
            .withRoomCode(this.roomCode)
            .withPlayer1Id(this.player1Id)
            .withPlayer2Id(this.player2Id)
            .withType(this.type)
            .withStatus(this.status)
            .withCreatedAt(this.createdAt)
            .withUpdatedAt(this.updatedAt)
            ;
    }
}