package com.goody.nus.se.gomoku.ranking.model.entity;

import jakarta.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   Experience rule configuration table
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table level_rule
 */
public class LevelRule implements Serializable {
    /**
     * Database Column Remarks:
     *   Primary key
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   Game mode type
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.mode_type")
    private String modeType;

    /**
     * Database Column Remarks:
     *   Match result
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.match_result")
    private String matchResult;

    /**
     * Database Column Remarks:
     *   Experience value change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.exp_value")
    private Integer expValue;

    /**
     * Database Column Remarks:
     *   Rule description
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.description")
    private String description;

    /**
     * Database Column Remarks:
     *   Creation time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.created_time")
    private LocalDateTime createdTime;

    /**
     * Database Column Remarks:
     *   Update time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.updated_time")
    private LocalDateTime updatedTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.mode_type")
    public String getModeType() {
        return modeType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withModeType(String modeType) {
        this.setModeType(modeType);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.mode_type")
    public void setModeType(String modeType) {
        this.modeType = modeType == null ? null : modeType.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.match_result")
    public String getMatchResult() {
        return matchResult;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withMatchResult(String matchResult) {
        this.setMatchResult(matchResult);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.match_result")
    public void setMatchResult(String matchResult) {
        this.matchResult = matchResult == null ? null : matchResult.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.exp_value")
    public Integer getExpValue() {
        return expValue;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withExpValue(Integer expValue) {
        this.setExpValue(expValue);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.exp_value")
    public void setExpValue(Integer expValue) {
        this.expValue = expValue;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.description")
    public String getDescription() {
        return description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.description")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.created_time")
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withCreatedTime(LocalDateTime createdTime) {
        this.setCreatedTime(createdTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.created_time")
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.updated_time")
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public LevelRule withUpdatedTime(LocalDateTime updatedTime) {
        this.setUpdatedTime(updatedTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: level_rule.updated_time")
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LevelRule other = (LevelRule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getModeType() == null ? other.getModeType() == null : this.getModeType().equals(other.getModeType()))
            && (this.getMatchResult() == null ? other.getMatchResult() == null : this.getMatchResult().equals(other.getMatchResult()))
            && (this.getExpValue() == null ? other.getExpValue() == null : this.getExpValue().equals(other.getExpValue()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getModeType() == null) ? 0 : getModeType().hashCode());
        result = prime * result + ((getMatchResult() == null) ? 0 : getMatchResult().hashCode());
        result = prime * result + ((getExpValue() == null) ? 0 : getExpValue().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: level_rule")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", modeType=").append(modeType);
        sb.append(", matchResult=").append(matchResult);
        sb.append(", expValue=").append(expValue);
        sb.append(", description=").append(description);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}