package com.goody.nus.se.gomoku.ranking.model.entity;

import jakarta.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   Player overall ranking table
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ranking
 */
public class Ranking implements Serializable {
    /**
     * Database Column Remarks:
     *   Primary key
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   Player ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.user_id")
    private Long userId;

    /**
     * Database Column Remarks:
     *   Leaderboard ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.leaderboard_rule_id")
    private Long leaderboardRuleId;

    /**
     * Database Column Remarks:
     *   Player total experience
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.total_exp")
    private Integer totalExp;

    /**
     * Database Column Remarks:
     *   Current level ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.level_id")
    private Long levelId;

    /**
     * Database Column Remarks:
     *   Current total score (only changes in ranked mode)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.current_total_score")
    private Integer currentTotalScore;

    /**
     * Database Column Remarks:
     *   Current ranking position (refresh periodically)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.rank_position")
    private Integer rankPosition;

    /**
     * Database Column Remarks:
     *   Creation time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.created_time")
    private LocalDateTime createdTime;

    /**
     * Database Column Remarks:
     *   Update time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.updated_time")
    private LocalDateTime updatedTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.user_id")
    public Long getUserId() {
        return userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.user_id")
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.leaderboard_rule_id")
    public Long getLeaderboardRuleId() {
        return leaderboardRuleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withLeaderboardRuleId(Long leaderboardRuleId) {
        this.setLeaderboardRuleId(leaderboardRuleId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.leaderboard_rule_id")
    public void setLeaderboardRuleId(Long leaderboardRuleId) {
        this.leaderboardRuleId = leaderboardRuleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.total_exp")
    public Integer getTotalExp() {
        return totalExp;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withTotalExp(Integer totalExp) {
        this.setTotalExp(totalExp);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.total_exp")
    public void setTotalExp(Integer totalExp) {
        this.totalExp = totalExp;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.level_id")
    public Long getLevelId() {
        return levelId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withLevelId(Long levelId) {
        this.setLevelId(levelId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.level_id")
    public void setLevelId(Long levelId) {
        this.levelId = levelId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.current_total_score")
    public Integer getCurrentTotalScore() {
        return currentTotalScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withCurrentTotalScore(Integer currentTotalScore) {
        this.setCurrentTotalScore(currentTotalScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.current_total_score")
    public void setCurrentTotalScore(Integer currentTotalScore) {
        this.currentTotalScore = currentTotalScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.rank_position")
    public Integer getRankPosition() {
        return rankPosition;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withRankPosition(Integer rankPosition) {
        this.setRankPosition(rankPosition);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.rank_position")
    public void setRankPosition(Integer rankPosition) {
        this.rankPosition = rankPosition;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.created_time")
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withCreatedTime(LocalDateTime createdTime) {
        this.setCreatedTime(createdTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.created_time")
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.updated_time")
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public Ranking withUpdatedTime(LocalDateTime updatedTime) {
        this.setUpdatedTime(updatedTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: ranking.updated_time")
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Ranking other = (Ranking) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLeaderboardRuleId() == null ? other.getLeaderboardRuleId() == null : this.getLeaderboardRuleId().equals(other.getLeaderboardRuleId()))
            && (this.getTotalExp() == null ? other.getTotalExp() == null : this.getTotalExp().equals(other.getTotalExp()))
            && (this.getLevelId() == null ? other.getLevelId() == null : this.getLevelId().equals(other.getLevelId()))
            && (this.getCurrentTotalScore() == null ? other.getCurrentTotalScore() == null : this.getCurrentTotalScore().equals(other.getCurrentTotalScore()))
            && (this.getRankPosition() == null ? other.getRankPosition() == null : this.getRankPosition().equals(other.getRankPosition()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLeaderboardRuleId() == null) ? 0 : getLeaderboardRuleId().hashCode());
        result = prime * result + ((getTotalExp() == null) ? 0 : getTotalExp().hashCode());
        result = prime * result + ((getLevelId() == null) ? 0 : getLevelId().hashCode());
        result = prime * result + ((getCurrentTotalScore() == null) ? 0 : getCurrentTotalScore().hashCode());
        result = prime * result + ((getRankPosition() == null) ? 0 : getRankPosition().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: ranking")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", leaderboardRuleId=").append(leaderboardRuleId);
        sb.append(", totalExp=").append(totalExp);
        sb.append(", levelId=").append(levelId);
        sb.append(", currentTotalScore=").append(currentTotalScore);
        sb.append(", rankPosition=").append(rankPosition);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}