package com.goody.nus.se.gomoku.ranking.model.entity;

import jakarta.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   Ranked mode match score record table
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table score
 */
public class Score implements Serializable {
    /**
     * Database Column Remarks:
     *   Primary key
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   Leaderboard ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.leaderboard_rule_id")
    private Long leaderboardRuleId;

    /**
     * Database Column Remarks:
     *   Player ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.user_id")
    private Long userId;

    /**
     * Database Column Remarks:
     *   Match ID (from match module)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.match_id")
    private Long matchId;

    /**
     * Database Column Remarks:
     *   Score rule ID (from score_rule)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.rule_id")
    private Long ruleId;

    /**
     * Database Column Remarks:
     *   Score change in this match
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.score_change")
    private Integer scoreChange;

    /**
     * Database Column Remarks:
     *   Player total score after match
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.final_score")
    private Integer finalScore;

    /**
     * Database Column Remarks:
     *   Match result
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.match_result")
    private String matchResult;

    /**
     * Database Column Remarks:
     *   Creation time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.created_time")
    private LocalDateTime createdTime;

    /**
     * Database Column Remarks:
     *   Update time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.updated_time")
    private LocalDateTime updatedTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.leaderboard_rule_id")
    public Long getLeaderboardRuleId() {
        return leaderboardRuleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withLeaderboardRuleId(Long leaderboardRuleId) {
        this.setLeaderboardRuleId(leaderboardRuleId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.leaderboard_rule_id")
    public void setLeaderboardRuleId(Long leaderboardRuleId) {
        this.leaderboardRuleId = leaderboardRuleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.user_id")
    public Long getUserId() {
        return userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.user_id")
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.match_id")
    public Long getMatchId() {
        return matchId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withMatchId(Long matchId) {
        this.setMatchId(matchId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.match_id")
    public void setMatchId(Long matchId) {
        this.matchId = matchId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.rule_id")
    public Long getRuleId() {
        return ruleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withRuleId(Long ruleId) {
        this.setRuleId(ruleId);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.rule_id")
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.score_change")
    public Integer getScoreChange() {
        return scoreChange;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withScoreChange(Integer scoreChange) {
        this.setScoreChange(scoreChange);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.score_change")
    public void setScoreChange(Integer scoreChange) {
        this.scoreChange = scoreChange;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.final_score")
    public Integer getFinalScore() {
        return finalScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withFinalScore(Integer finalScore) {
        this.setFinalScore(finalScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.final_score")
    public void setFinalScore(Integer finalScore) {
        this.finalScore = finalScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.match_result")
    public String getMatchResult() {
        return matchResult;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withMatchResult(String matchResult) {
        this.setMatchResult(matchResult);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.match_result")
    public void setMatchResult(String matchResult) {
        this.matchResult = matchResult == null ? null : matchResult.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.created_time")
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withCreatedTime(LocalDateTime createdTime) {
        this.setCreatedTime(createdTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.created_time")
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.updated_time")
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public Score withUpdatedTime(LocalDateTime updatedTime) {
        this.setUpdatedTime(updatedTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score.updated_time")
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Score other = (Score) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLeaderboardRuleId() == null ? other.getLeaderboardRuleId() == null : this.getLeaderboardRuleId().equals(other.getLeaderboardRuleId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getMatchId() == null ? other.getMatchId() == null : this.getMatchId().equals(other.getMatchId()))
            && (this.getRuleId() == null ? other.getRuleId() == null : this.getRuleId().equals(other.getRuleId()))
            && (this.getScoreChange() == null ? other.getScoreChange() == null : this.getScoreChange().equals(other.getScoreChange()))
            && (this.getFinalScore() == null ? other.getFinalScore() == null : this.getFinalScore().equals(other.getFinalScore()))
            && (this.getMatchResult() == null ? other.getMatchResult() == null : this.getMatchResult().equals(other.getMatchResult()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLeaderboardRuleId() == null) ? 0 : getLeaderboardRuleId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getMatchId() == null) ? 0 : getMatchId().hashCode());
        result = prime * result + ((getRuleId() == null) ? 0 : getRuleId().hashCode());
        result = prime * result + ((getScoreChange() == null) ? 0 : getScoreChange().hashCode());
        result = prime * result + ((getFinalScore() == null) ? 0 : getFinalScore().hashCode());
        result = prime * result + ((getMatchResult() == null) ? 0 : getMatchResult().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", leaderboardRuleId=").append(leaderboardRuleId);
        sb.append(", userId=").append(userId);
        sb.append(", matchId=").append(matchId);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", scoreChange=").append(scoreChange);
        sb.append(", finalScore=").append(finalScore);
        sb.append(", matchResult=").append(matchResult);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}