package com.goody.nus.se.gomoku.ranking.model.entity;

import jakarta.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   Score rule configuration table (flattened structure for all modes and results)
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table score_rule
 */
public class ScoreRule implements Serializable {
    /**
     * Database Column Remarks:
     *   Primary key
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   Rule name (e.g., Standard, Season1, etc.)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.rule_name")
    private String ruleName;

    /**
     * Database Column Remarks:
     *   RANKED mode WIN score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_win_score")
    private Integer rankedWinScore;

    /**
     * Database Column Remarks:
     *   RANKED mode LOSE score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_lose_score")
    private Integer rankedLoseScore;

    /**
     * Database Column Remarks:
     *   RANKED mode DRAW score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_draw_score")
    private Integer rankedDrawScore;

    /**
     * Database Column Remarks:
     *   CASUAL mode WIN score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_win_score")
    private Integer casualWinScore;

    /**
     * Database Column Remarks:
     *   CASUAL mode LOSE score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_lose_score")
    private Integer casualLoseScore;

    /**
     * Database Column Remarks:
     *   CASUAL mode DRAW score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_draw_score")
    private Integer casualDrawScore;

    /**
     * Database Column Remarks:
     *   PRIVATE mode WIN score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_win_score")
    private Integer privateWinScore;

    /**
     * Database Column Remarks:
     *   PRIVATE mode LOSE score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_lose_score")
    private Integer privateLoseScore;

    /**
     * Database Column Remarks:
     *   PRIVATE mode DRAW score change
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_draw_score")
    private Integer privateDrawScore;

    /**
     * Database Column Remarks:
     *   Rule description
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.description")
    private String description;

    /**
     * Database Column Remarks:
     *   Creation time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.created_time")
    private LocalDateTime createdTime;

    /**
     * Database Column Remarks:
     *   Update time
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.updated_time")
    private LocalDateTime updatedTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.rule_name")
    public String getRuleName() {
        return ruleName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withRuleName(String ruleName) {
        this.setRuleName(ruleName);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.rule_name")
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_win_score")
    public Integer getRankedWinScore() {
        return rankedWinScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withRankedWinScore(Integer rankedWinScore) {
        this.setRankedWinScore(rankedWinScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_win_score")
    public void setRankedWinScore(Integer rankedWinScore) {
        this.rankedWinScore = rankedWinScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_lose_score")
    public Integer getRankedLoseScore() {
        return rankedLoseScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withRankedLoseScore(Integer rankedLoseScore) {
        this.setRankedLoseScore(rankedLoseScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_lose_score")
    public void setRankedLoseScore(Integer rankedLoseScore) {
        this.rankedLoseScore = rankedLoseScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_draw_score")
    public Integer getRankedDrawScore() {
        return rankedDrawScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withRankedDrawScore(Integer rankedDrawScore) {
        this.setRankedDrawScore(rankedDrawScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.ranked_draw_score")
    public void setRankedDrawScore(Integer rankedDrawScore) {
        this.rankedDrawScore = rankedDrawScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_win_score")
    public Integer getCasualWinScore() {
        return casualWinScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withCasualWinScore(Integer casualWinScore) {
        this.setCasualWinScore(casualWinScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_win_score")
    public void setCasualWinScore(Integer casualWinScore) {
        this.casualWinScore = casualWinScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_lose_score")
    public Integer getCasualLoseScore() {
        return casualLoseScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withCasualLoseScore(Integer casualLoseScore) {
        this.setCasualLoseScore(casualLoseScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_lose_score")
    public void setCasualLoseScore(Integer casualLoseScore) {
        this.casualLoseScore = casualLoseScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_draw_score")
    public Integer getCasualDrawScore() {
        return casualDrawScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withCasualDrawScore(Integer casualDrawScore) {
        this.setCasualDrawScore(casualDrawScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.casual_draw_score")
    public void setCasualDrawScore(Integer casualDrawScore) {
        this.casualDrawScore = casualDrawScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_win_score")
    public Integer getPrivateWinScore() {
        return privateWinScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withPrivateWinScore(Integer privateWinScore) {
        this.setPrivateWinScore(privateWinScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_win_score")
    public void setPrivateWinScore(Integer privateWinScore) {
        this.privateWinScore = privateWinScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_lose_score")
    public Integer getPrivateLoseScore() {
        return privateLoseScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withPrivateLoseScore(Integer privateLoseScore) {
        this.setPrivateLoseScore(privateLoseScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_lose_score")
    public void setPrivateLoseScore(Integer privateLoseScore) {
        this.privateLoseScore = privateLoseScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_draw_score")
    public Integer getPrivateDrawScore() {
        return privateDrawScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withPrivateDrawScore(Integer privateDrawScore) {
        this.setPrivateDrawScore(privateDrawScore);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.private_draw_score")
    public void setPrivateDrawScore(Integer privateDrawScore) {
        this.privateDrawScore = privateDrawScore;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.description")
    public String getDescription() {
        return description;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.description")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.created_time")
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withCreatedTime(LocalDateTime createdTime) {
        this.setCreatedTime(createdTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.created_time")
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.updated_time")
    public LocalDateTime getUpdatedTime() {
        return updatedTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public ScoreRule withUpdatedTime(LocalDateTime updatedTime) {
        this.setUpdatedTime(updatedTime);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: score_rule.updated_time")
    public void setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScoreRule other = (ScoreRule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRuleName() == null ? other.getRuleName() == null : this.getRuleName().equals(other.getRuleName()))
            && (this.getRankedWinScore() == null ? other.getRankedWinScore() == null : this.getRankedWinScore().equals(other.getRankedWinScore()))
            && (this.getRankedLoseScore() == null ? other.getRankedLoseScore() == null : this.getRankedLoseScore().equals(other.getRankedLoseScore()))
            && (this.getRankedDrawScore() == null ? other.getRankedDrawScore() == null : this.getRankedDrawScore().equals(other.getRankedDrawScore()))
            && (this.getCasualWinScore() == null ? other.getCasualWinScore() == null : this.getCasualWinScore().equals(other.getCasualWinScore()))
            && (this.getCasualLoseScore() == null ? other.getCasualLoseScore() == null : this.getCasualLoseScore().equals(other.getCasualLoseScore()))
            && (this.getCasualDrawScore() == null ? other.getCasualDrawScore() == null : this.getCasualDrawScore().equals(other.getCasualDrawScore()))
            && (this.getPrivateWinScore() == null ? other.getPrivateWinScore() == null : this.getPrivateWinScore().equals(other.getPrivateWinScore()))
            && (this.getPrivateLoseScore() == null ? other.getPrivateLoseScore() == null : this.getPrivateLoseScore().equals(other.getPrivateLoseScore()))
            && (this.getPrivateDrawScore() == null ? other.getPrivateDrawScore() == null : this.getPrivateDrawScore().equals(other.getPrivateDrawScore()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRuleName() == null) ? 0 : getRuleName().hashCode());
        result = prime * result + ((getRankedWinScore() == null) ? 0 : getRankedWinScore().hashCode());
        result = prime * result + ((getRankedLoseScore() == null) ? 0 : getRankedLoseScore().hashCode());
        result = prime * result + ((getRankedDrawScore() == null) ? 0 : getRankedDrawScore().hashCode());
        result = prime * result + ((getCasualWinScore() == null) ? 0 : getCasualWinScore().hashCode());
        result = prime * result + ((getCasualLoseScore() == null) ? 0 : getCasualLoseScore().hashCode());
        result = prime * result + ((getCasualDrawScore() == null) ? 0 : getCasualDrawScore().hashCode());
        result = prime * result + ((getPrivateWinScore() == null) ? 0 : getPrivateWinScore().hashCode());
        result = prime * result + ((getPrivateLoseScore() == null) ? 0 : getPrivateLoseScore().hashCode());
        result = prime * result + ((getPrivateDrawScore() == null) ? 0 : getPrivateDrawScore().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: score_rule")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ruleName=").append(ruleName);
        sb.append(", rankedWinScore=").append(rankedWinScore);
        sb.append(", rankedLoseScore=").append(rankedLoseScore);
        sb.append(", rankedDrawScore=").append(rankedDrawScore);
        sb.append(", casualWinScore=").append(casualWinScore);
        sb.append(", casualLoseScore=").append(casualLoseScore);
        sb.append(", casualDrawScore=").append(casualDrawScore);
        sb.append(", privateWinScore=").append(privateWinScore);
        sb.append(", privateLoseScore=").append(privateLoseScore);
        sb.append(", privateDrawScore=").append(privateDrawScore);
        sb.append(", description=").append(description);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}