package com.goody.nus.se.gomoku.user.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.user.model.dao.UserTokenMapper;
import com.goody.nus.se.gomoku.user.model.dao.customer.CustomerUserTokenMapper;
import com.goody.nus.se.gomoku.user.model.dto.UserTokenDTO;
import com.goody.nus.se.gomoku.user.model.entity.UserToken;
import com.goody.nus.se.gomoku.user.service.interfaces.IUserTokenService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Service implementation for UserToken
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class UserTokenServiceImpl implements IUserTokenService {
    @Autowired
    private UserTokenMapper userTokenMapper;

    @Autowired
    private CustomerUserTokenMapper customerUserTokenMapper;

    @Override
    public Long save(UserTokenDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        UserToken entity = dto.toEntity();
        int result = userTokenMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<UserTokenDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<UserToken> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedAt() == null) {
                        dto.setCreatedAt(LocalDateTime.now());
                    }
                    if (dto.getUpdatedAt() == null) {
                        dto.setUpdatedAt(LocalDateTime.now());
                    }
                })
                .map(UserTokenDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return userTokenMapper.insertMultiple(entityList);
    }

    @Override
    public int update(UserTokenDTO dto) {
        if (dto == null) {
            return 0;
        }

        UserToken entity = dto.toEntity();
        return userTokenMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return userTokenMapper.deleteByPrimaryKey(id);
    }

    @Override
    public UserTokenDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        UserToken entity = userTokenMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? UserTokenDTO.fromEntity(entity) : null;
    }

    @Override
    public List<UserTokenDTO> findAll() {
        List<UserToken> entityList = userTokenMapper.select(c -> c);
        return entityList.stream()
                .map(UserTokenDTO::fromEntity)
                .collect(Collectors.toList());
    }

    @Override
    public UserTokenDTO findByUserId(Long userId) {
        if (userId == null) {
            return null;
        }

        UserToken entity = customerUserTokenMapper.selectByUserId(userId);
        return entity != null ? UserTokenDTO.fromEntity(entity) : null;
    }

    @Override
    public UserTokenDTO findByRefreshToken(String refreshToken) {
        if (refreshToken == null || refreshToken.isEmpty()) {
            return null;
        }

        UserToken entity = customerUserTokenMapper.selectByRefreshToken(refreshToken);
        return entity != null ? UserTokenDTO.fromEntity(entity) : null;
    }

    @Override
    public int deleteByUserId(Long userId) {
        if (userId == null) {
            return 0;
        }

        return customerUserTokenMapper.deleteByUserId(userId);
    }

    @Override
    public int saveOrUpdate(UserTokenDTO dto) {
        if (dto == null || dto.getUserId() == null) {
            return 0;
        }

        // Check if user already has a token
        UserTokenDTO existing = findByUserId(dto.getUserId());

        if (existing != null) {
            // Update existing token
            dto.setId(existing.getId());
            return update(dto);
        } else {
            // Insert new token
            Long id = save(dto);
            return id != null ? 1 : 0;
        }
    }
}
