package com.goody.nus.se.gomoku.user.service.impl;

import com.goody.nus.se.gomoku.common.basiccheck.BasicCheck;
import com.goody.nus.se.gomoku.common.basiccheck.CheckString;
import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.user.model.dao.UserDynamicSqlSupport;
import com.goody.nus.se.gomoku.user.model.dao.UserMapper;
import com.goody.nus.se.gomoku.user.model.dto.UserDTO;
import com.goody.nus.se.gomoku.user.model.entity.User;
import com.goody.nus.se.gomoku.user.service.interfaces.IUserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;

/**
 * Service implementation for User
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class UserServiceImpl implements IUserService {
    @Autowired
    private UserMapper userMapper;

    @Override
    public Long save(UserDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        User entity = dto.toEntity();
        int result = userMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<UserDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<User> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedAt() == null) {
                        dto.setCreatedAt(LocalDateTime.now());
                    }
                    if (dto.getUpdatedAt() == null) {
                        dto.setUpdatedAt(LocalDateTime.now());
                    }
                })
                .map(UserDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return userMapper.insertMultiple(entityList);
    }

    @Override
    public int update(UserDTO dto) {
        if (dto == null) {
            return 0;
        }

        User entity = dto.toEntity();
        return userMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return userMapper.deleteByPrimaryKey(id);
    }

    @Override
    public UserDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        User entity = userMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? UserDTO.fromEntity(entity) : null;
    }

    @Override
    public List<UserDTO> findAll() {
        List<User> entityList = userMapper.select(c -> c);
        return entityList.stream()
                .map(UserDTO::fromEntity)
                .collect(Collectors.toList());
    }

    @Override
    @BasicCheck
    public UserDTO findByEmail(@CheckString String email) {
        User entity = userMapper.selectOne(c -> c
                .where(UserDynamicSqlSupport.email, isEqualTo(email))
                .and(UserDynamicSqlSupport.status, isEqualTo((byte) 1))
                .limit(1L)
        ).orElse(null);
        return entity != null ? UserDTO.fromEntity(entity) : null;
    }

    @Override
    @BasicCheck
    public UserDTO findByNickname(@CheckString String nickname) {
        User entity = userMapper.selectOne(c -> c
                .where(UserDynamicSqlSupport.nickname, isEqualTo(nickname))
                .and(UserDynamicSqlSupport.status, isEqualTo((byte) 1))
                .limit(1L)
        ).orElse(null);
        return entity != null ? UserDTO.fromEntity(entity) : null;
    }

    @Override
    @BasicCheck
    public boolean existsByEmail(@CheckString String email) {
        return userMapper.count(c -> c
                .where(UserDynamicSqlSupport.email, isEqualTo(email))
        ) > 0;
    }

    @Override
    @BasicCheck
    public boolean existsByNickname(@CheckString String nickname) {
        return userMapper.count(c -> c
                .where(UserDynamicSqlSupport.nickname, isEqualTo(nickname))
        ) > 0;
    }
}
