package com.goody.nus.se.gomoku.user.model.entity;

import jakarta.annotation.Generated;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 * User Token Table
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_token
 */
public class UserToken implements Serializable {
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * Primary Key
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.id")
    private Long id;
    /**
     * Database Column Remarks:
     * User ID
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.user_id")
    private Long userId;
    /**
     * Database Column Remarks:
     * Refresh Token (UUID)
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.refresh_token")
    private String refreshToken;
    /**
     * Database Column Remarks:
     * Expiration time
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.expires_at")
    private LocalDateTime expiresAt;
    /**
     * Database Column Remarks:
     * Creation time
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.created_at")
    private LocalDateTime createdAt;
    /**
     * Database Column Remarks:
     * Update time
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.updated_at")
    private LocalDateTime updatedAt;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.id")
    public Long getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public UserToken withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.user_id")
    public Long getUserId() {
        return userId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.user_id")
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public UserToken withUserId(Long userId) {
        this.setUserId(userId);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.refresh_token")
    public String getRefreshToken() {
        return refreshToken;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.refresh_token")
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public UserToken withRefreshToken(String refreshToken) {
        this.setRefreshToken(refreshToken);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.expires_at")
    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.expires_at")
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public UserToken withExpiresAt(LocalDateTime expiresAt) {
        this.setExpiresAt(expiresAt);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.created_at")
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.created_at")
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public UserToken withCreatedAt(LocalDateTime createdAt) {
        this.setCreatedAt(createdAt);
        return this;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.updated_at")
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user_token.updated_at")
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public UserToken withUpdatedAt(LocalDateTime updatedAt) {
        this.setUpdatedAt(updatedAt);
        return this;
    }

    @Override
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserToken other = (UserToken) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getRefreshToken() == null ? other.getRefreshToken() == null : this.getRefreshToken().equals(other.getRefreshToken()))
                && (this.getExpiresAt() == null ? other.getExpiresAt() == null : this.getExpiresAt().equals(other.getExpiresAt()))
                && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
                && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()));
    }

    @Override
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRefreshToken() == null) ? 0 : getRefreshToken().hashCode());
        result = prime * result + ((getExpiresAt() == null) ? 0 : getExpiresAt().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        return result;
    }

    @Override
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source Table: user_token")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", refreshToken=").append(refreshToken);
        sb.append(", expiresAt=").append(expiresAt);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
