package com.goody.nus.se.gomoku.common.mybatis;

import org.mybatis.generator.api.GeneratedJavaFile;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.JavaVisibility;

import java.util.ArrayList;
import java.util.List;

/**
 * Customer Mapper Generation Plugin
 * Generates custom mapper interfaces that extend the original generated mappers
 *
 * @author Goody
 * @version 1.0, 2024/12/24
 * @since 1.0.0
 */
public class CustomerMapperPlugin extends PluginAdapter {

    private static final String CUSTOMER_PREFIX = "Customer";
    private static final String CUSTOMER_PACKAGE = "customer";

    @Override
    public boolean validate(List<String> warnings) {
        return true;
    }

    @Override
    public List<GeneratedJavaFile> contextGenerateAdditionalJavaFiles(IntrospectedTable introspectedTable) {
        List<GeneratedJavaFile> answer = new ArrayList<>();

        // Generate Customer Mapper interface
        Interface customerMapperInterface = generateCustomerMapperInterface(introspectedTable);
        GeneratedJavaFile customerMapperJavaFile = new GeneratedJavaFile(customerMapperInterface,
                context.getJavaClientGeneratorConfiguration().getTargetProject(),
                context.getProperty("javaFileEncoding"),
                context.getJavaFormatter());

        answer.add(customerMapperJavaFile);

        return answer;
    }

    private Interface generateCustomerMapperInterface(IntrospectedTable introspectedTable) {
        // Get original mapper info
        String originalMapperType = introspectedTable.getMyBatis3JavaMapperType();
        String originalMapperPackage = originalMapperType.substring(0, originalMapperType.lastIndexOf('.'));
        String originalMapperClassName = originalMapperType.substring(originalMapperType.lastIndexOf('.') + 1);

        // Remove "Mapper" suffix and add "Customer" prefix
        String entityName = originalMapperClassName.replace("Mapper", "");
        String customerMapperClassName = CUSTOMER_PREFIX + entityName + "Mapper";

        // Generate customer mapper package
        String customerMapperPackage = originalMapperPackage.replace(".dao", ".dao." + CUSTOMER_PACKAGE);
        String customerMapperFullType = customerMapperPackage + "." + customerMapperClassName;

        // Create customer mapper interface
        FullyQualifiedJavaType customerMapperType = new FullyQualifiedJavaType(customerMapperFullType);
        Interface customerMapperInterface = new Interface(customerMapperType);

        // Set interface properties
        customerMapperInterface.setVisibility(JavaVisibility.PUBLIC);

        // Add imports
        FullyQualifiedJavaType mapperAnnotationType = new FullyQualifiedJavaType("org.apache.ibatis.annotations.Mapper");
        customerMapperInterface.addImportedType(mapperAnnotationType);

        // Add @Mapper annotation
        customerMapperInterface.addAnnotation("@Mapper");

        // Add interface comment
        customerMapperInterface.addJavaDocLine("/**");
        customerMapperInterface.addJavaDocLine(" * Customer Mapper for " + entityName);
        customerMapperInterface.addJavaDocLine(" * Add custom queries here");
        customerMapperInterface.addJavaDocLine(" * Generated by MyBatis Generator Customer Mapper Plugin");
        customerMapperInterface.addJavaDocLine(" */");

        return customerMapperInterface;
    }
}