package com.goody.nus.se.gomoku.ranking.model.dao.customer;

import org.apache.ibatis.annotations.Mapper;

/**
 * Customer Mapper for LevelRule
 * Add custom queries here
 * Generated by MyBatis Generator Customer Mapper Plugin
 */
@Mapper
public interface CustomerLevelRuleMapper {
}