package com.goody.nus.se.gomoku.ranking.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.ranking.model.dao.LeaderboardRuleDynamicSqlSupport;
import com.goody.nus.se.gomoku.ranking.model.dao.LeaderboardRuleMapper;
import com.goody.nus.se.gomoku.ranking.model.dao.customer.CustomerLeaderboardRuleMapper;
import com.goody.nus.se.gomoku.ranking.model.dto.LeaderboardRuleDTO;
import com.goody.nus.se.gomoku.ranking.model.entity.LeaderboardRule;
import com.goody.nus.se.gomoku.ranking.service.interfaces.ILeaderboardRuleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;
import static org.mybatis.dynamic.sql.SqlBuilder.isGreaterThanOrEqualTo;
import static org.mybatis.dynamic.sql.SqlBuilder.isLessThanOrEqualTo;

/**
 * Service implementation for LeaderboardRule
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class LeaderboardRuleServiceImpl implements ILeaderboardRuleService {
    @Autowired
    private LeaderboardRuleMapper leaderboardRuleMapper;

    @Autowired
    private CustomerLeaderboardRuleMapper customerLeaderboardRuleMapper;

    @Override
    public Long save(LeaderboardRuleDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        LeaderboardRule entity = dto.toEntity();
        int result = leaderboardRuleMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<LeaderboardRuleDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<LeaderboardRule> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedTime() == null) {
                        dto.setCreatedTime(LocalDateTime.now());
                    }
                    if (dto.getUpdatedTime() == null) {
                        dto.setUpdatedTime(LocalDateTime.now());
                    }
                })
                .map(LeaderboardRuleDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return leaderboardRuleMapper.insertMultiple(entityList);
    }

    @Override
    public int update(LeaderboardRuleDTO dto) {
        if (dto == null) {
            return 0;
        }

        LeaderboardRule entity = dto.toEntity();
        return leaderboardRuleMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return leaderboardRuleMapper.deleteByPrimaryKey(id);
    }

    @Override
    public LeaderboardRuleDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        LeaderboardRule entity = leaderboardRuleMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? LeaderboardRuleDTO.fromEntity(entity) : null;
    }

    @Override
    public List<LeaderboardRuleDTO> findAll() {
        List<LeaderboardRule> entityList = leaderboardRuleMapper.select(c -> c);
        return entityList.stream()
                .map(LeaderboardRuleDTO::fromEntity)
                .collect(Collectors.toList());
    }

    // ==================== Custom Query Methods Implementation ====================

    @Override
    public List<LeaderboardRuleDTO> findActiveRules(int currentTime) {
        List<LeaderboardRule> entityList = leaderboardRuleMapper.select(c ->
                c.where(LeaderboardRuleDynamicSqlSupport.startTime, isLessThanOrEqualTo(currentTime))
                        .and(LeaderboardRuleDynamicSqlSupport.endTime, isGreaterThanOrEqualTo(currentTime))
        );
        return entityList.stream()
                .map(LeaderboardRuleDTO::fromEntity)
                .collect(Collectors.toList());
    }

    @Override
    public LeaderboardRuleDTO findByType(String type) {
        if (type == null) {
            return null;
        }
        LeaderboardRule entity = leaderboardRuleMapper.selectOne(c ->
                c.where(LeaderboardRuleDynamicSqlSupport.type, isEqualTo(type))
                        .limit(1)
        ).orElse(null);
        return entity != null ? LeaderboardRuleDTO.fromEntity(entity) : null;
    }

    @Override
    public LeaderboardRuleDTO findActiveRuleByType(String type, int currentTime) {
        if (type == null) {
            return null;
        }
        LeaderboardRule entity = leaderboardRuleMapper.selectOne(c ->
                c.where(LeaderboardRuleDynamicSqlSupport.type, isEqualTo(type))
                        .and(LeaderboardRuleDynamicSqlSupport.startTime, isLessThanOrEqualTo(currentTime))
                        .and(LeaderboardRuleDynamicSqlSupport.endTime, isGreaterThanOrEqualTo(currentTime))
                        .limit(1)
        ).orElse(null);
        return entity != null ? LeaderboardRuleDTO.fromEntity(entity) : null;
    }
}
