package com.goody.nus.se.gomoku.ranking.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.ranking.model.dao.LevelMapper;
import com.goody.nus.se.gomoku.ranking.model.dao.customer.CustomerLevelMapper;
import com.goody.nus.se.gomoku.ranking.model.dto.LevelDTO;
import com.goody.nus.se.gomoku.ranking.model.entity.Level;
import com.goody.nus.se.gomoku.ranking.service.interfaces.ILevelService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Service implementation for Level
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class LevelServiceImpl implements ILevelService {
    @Autowired
    private LevelMapper levelMapper;

    @Autowired
    private CustomerLevelMapper customerLevelMapper;

    @Override
    public Long save(LevelDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        Level entity = dto.toEntity();
        int result = levelMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<LevelDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<Level> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedTime() == null) {
                        dto.setCreatedTime(LocalDateTime.now());
                    }
                    if (dto.getUpdatedTime() == null) {
                        dto.setUpdatedTime(LocalDateTime.now());
                    }
                })
                .map(LevelDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return levelMapper.insertMultiple(entityList);
    }

    @Override
    public int update(LevelDTO dto) {
        if (dto == null) {
            return 0;
        }

        Level entity = dto.toEntity();
        return levelMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return levelMapper.deleteByPrimaryKey(id);
    }

    @Override
    public LevelDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        Level entity = levelMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? LevelDTO.fromEntity(entity) : null;
    }

    @Override
    public List<LevelDTO> findAll() {
        List<Level> entityList = levelMapper.select(c -> c);
        return entityList.stream()
                .map(LevelDTO::fromEntity)
                .collect(Collectors.toList());
    }
}
