package com.goody.nus.se.gomoku.ranking.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.ranking.model.dao.LevelRuleDynamicSqlSupport;
import com.goody.nus.se.gomoku.ranking.model.dao.LevelRuleMapper;
import com.goody.nus.se.gomoku.ranking.model.dao.customer.CustomerLevelRuleMapper;
import com.goody.nus.se.gomoku.ranking.model.dto.LevelRuleDTO;
import com.goody.nus.se.gomoku.ranking.model.entity.LevelRule;
import com.goody.nus.se.gomoku.ranking.service.interfaces.ILevelRuleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;

/**
 * Service implementation for LevelRule
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class LevelRuleServiceImpl implements ILevelRuleService {
    @Autowired
    private LevelRuleMapper levelRuleMapper;

    @Autowired
    private CustomerLevelRuleMapper customerLevelRuleMapper;

    @Override
    public Long save(LevelRuleDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        LevelRule entity = dto.toEntity();
        int result = levelRuleMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<LevelRuleDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<LevelRule> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedTime() == null) {
                        dto.setCreatedTime(LocalDateTime.now());
                    }
                    if (dto.getUpdatedTime() == null) {
                        dto.setUpdatedTime(LocalDateTime.now());
                    }
                })
                .map(LevelRuleDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return levelRuleMapper.insertMultiple(entityList);
    }

    @Override
    public int update(LevelRuleDTO dto) {
        if (dto == null) {
            return 0;
        }

        LevelRule entity = dto.toEntity();
        return levelRuleMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return levelRuleMapper.deleteByPrimaryKey(id);
    }

    @Override
    public LevelRuleDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        LevelRule entity = levelRuleMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? LevelRuleDTO.fromEntity(entity) : null;
    }

    @Override
    public List<LevelRuleDTO> findAll() {
        List<LevelRule> entityList = levelRuleMapper.select(c -> c);
        return entityList.stream()
                .map(LevelRuleDTO::fromEntity)
                .collect(Collectors.toList());
    }

    @Override
    public LevelRuleDTO findByModeTypeAndMatchResult(String modeType, String matchResult) {
        if (modeType == null || matchResult == null) {
            return null;
        }
        LevelRule entity = levelRuleMapper.selectOne(c ->
                c.where(LevelRuleDynamicSqlSupport.modeType, isEqualTo(modeType))
                        .and(LevelRuleDynamicSqlSupport.matchResult, isEqualTo(matchResult))
                        .limit(1)
        ).orElse(null);
        return entity != null ? LevelRuleDTO.fromEntity(entity) : null;
    }

}
