package com.goody.nus.se.gomoku.ranking.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.ranking.model.dao.ScoreRuleDynamicSqlSupport;
import com.goody.nus.se.gomoku.ranking.model.dao.ScoreRuleMapper;
import com.goody.nus.se.gomoku.ranking.model.dao.customer.CustomerScoreRuleMapper;
import com.goody.nus.se.gomoku.ranking.model.dto.ScoreRuleDTO;
import com.goody.nus.se.gomoku.ranking.model.entity.ScoreRule;
import com.goody.nus.se.gomoku.ranking.service.interfaces.IScoreRuleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;

/**
 * Service implementation for ScoreRule
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class ScoreRuleServiceImpl implements IScoreRuleService {
    @Autowired
    private ScoreRuleMapper scoreRuleMapper;

    @Autowired
    private CustomerScoreRuleMapper customerScoreRuleMapper;

    @Override
    public Long save(ScoreRuleDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        ScoreRule entity = dto.toEntity();
        int result = scoreRuleMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<ScoreRuleDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<ScoreRule> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedTime() == null) {
                        dto.setCreatedTime(LocalDateTime.now());
                    }
                    if (dto.getUpdatedTime() == null) {
                        dto.setUpdatedTime(LocalDateTime.now());
                    }
                })
                .map(ScoreRuleDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return scoreRuleMapper.insertMultiple(entityList);
    }

    @Override
    public int update(ScoreRuleDTO dto) {
        if (dto == null) {
            return 0;
        }

        ScoreRule entity = dto.toEntity();
        return scoreRuleMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return scoreRuleMapper.deleteByPrimaryKey(id);
    }

    @Override
    public ScoreRuleDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        ScoreRule entity = scoreRuleMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? ScoreRuleDTO.fromEntity(entity) : null;
    }

    @Override
    public List<ScoreRuleDTO> findAll() {
        List<ScoreRule> entityList = scoreRuleMapper.select(c -> c);
        return entityList.stream()
                .map(ScoreRuleDTO::fromEntity)
                .collect(Collectors.toList());
    }
}
