package com.goody.nus.se.gomoku.ranking.service.impl;

import com.goody.nus.se.gomoku.common.util.UidGeneratorUtil;
import com.goody.nus.se.gomoku.ranking.model.dao.ScoreDynamicSqlSupport;
import com.goody.nus.se.gomoku.ranking.model.dao.ScoreMapper;
import com.goody.nus.se.gomoku.ranking.model.dao.customer.CustomerScoreMapper;
import com.goody.nus.se.gomoku.ranking.model.dto.ScoreDTO;
import com.goody.nus.se.gomoku.ranking.model.entity.Score;
import com.goody.nus.se.gomoku.ranking.service.interfaces.IScoreService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;

/**
 * Service implementation for Score
 * Generated by MyBatis Generator Service Plugin
 */
@Service
public class ScoreServiceImpl implements IScoreService {
    @Autowired
    private ScoreMapper scoreMapper;

    @Autowired
    private CustomerScoreMapper customerScoreMapper;

    @Override
    public Long save(ScoreDTO dto) {
        if (dto == null) {
            return null;
        }

        if (dto.getId() == null) {
            dto.setId(UidGeneratorUtil.generateUid());
        }

        Score entity = dto.toEntity();
        int result = scoreMapper.insertSelective(entity);
        return result > 0 ? entity.getId() : null;
    }

    @Override
    public int saveBatch(List<ScoreDTO> dtoList) {
        if (dtoList == null || dtoList.isEmpty()) {
            return 0;
        }

        List<Score> entityList = dtoList.stream()
                .filter(dto -> dto != null)
                .peek(dto -> {
                    if (dto.getId() == null) {
                        dto.setId(UidGeneratorUtil.generateUid());
                    }
                    if (dto.getCreatedTime() == null) {
                        dto.setCreatedTime(LocalDateTime.now());
                    }
                    if (dto.getUpdatedTime() == null) {
                        dto.setUpdatedTime(LocalDateTime.now());
                    }
                })
                .map(ScoreDTO::toEntity)
                .collect(Collectors.toList());

        if (entityList.isEmpty()) {
            return 0;
        }

        return scoreMapper.insertMultiple(entityList);
    }

    @Override
    public int update(ScoreDTO dto) {
        if (dto == null) {
            return 0;
        }

        Score entity = dto.toEntity();
        return scoreMapper.updateByPrimaryKeySelective(entity);
    }

    @Override
    public int deleteById(Long id) {
        if (id == null) {
            return 0;
        }

        return scoreMapper.deleteByPrimaryKey(id);
    }

    @Override
    public ScoreDTO findById(Long id) {
        if (id == null) {
            return null;
        }

        Score entity = scoreMapper.selectByPrimaryKey(id).orElse(null);
        return entity != null ? ScoreDTO.fromEntity(entity) : null;
    }

    @Override
    public List<ScoreDTO> findAll() {
        List<Score> entityList = scoreMapper.select(c -> c);
        return entityList.stream()
                .map(ScoreDTO::fromEntity)
                .collect(Collectors.toList());
    }

    // ==================== Custom Query Methods Implementation ====================

    @Override
    public List<ScoreDTO> findByUserIdAndLeaderboardRuleId(Long userId, Long leaderboardRuleId) {
        if (userId == null || leaderboardRuleId == null) {
            return List.of();
        }
        List<Score> entityList = scoreMapper.select(c ->
                c.where(ScoreDynamicSqlSupport.userId, isEqualTo(userId))
                        .and(ScoreDynamicSqlSupport.leaderboardRuleId, isEqualTo(leaderboardRuleId))
        );
        return entityList.stream()
                .map(ScoreDTO::fromEntity)
                .collect(Collectors.toList());
    }

    @Override
    public long countByMatchId(Long matchId) {
        if (matchId == null) {
            return 0;
        }
        return scoreMapper.count(c ->
                c.where(ScoreDynamicSqlSupport.matchId, isEqualTo(matchId))
        );
    }
}
